spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lockdb
    username: lockdb
    password: lockdb
  jpa:
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
